services:
  chat_server_1:
    build: .
    container_name: chat_server_1
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000

  chat_server_2:
    build: .
    container_name: chat_server_2
    restart: always
    ports:
      - "4001:4001"
    environment:
      - PORT=4001

  postgres_db:
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  nginx_proxy:
    image: nginx:alpine
    container_name: chat_app_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/sites-available
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - chat_server_1
      - chat_server_2

volumes:
  pgdata:
