apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chat-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: "chat-service-4000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: chat-web.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chat-service-4000
                port:
                  number: 4000
