apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-proxy-pod
  template:
    metadata:
      labels:
        app: nginx-proxy-pod
    spec:
      containers:
        - name: nginx

          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
